TRUNCATE TABLE companies;

INSERT INTO companies (id, display_name, description, company_url, icon_url)
VALUES ('1A2b3C4d5E6f7G8h9I0j1K2l3M', '株式会社アルファ', 'IT関連のサービスを提供', 'https://alpha.co.jp',
        'https://alpha.co.jp/icon.png'),
       ('2B3c4D5e6F7g8H9i0J1k2L3m4N', '株式会社ブラボー', '製造業界のリーダー', 'https://bravo.co.jp',
        'https://bravo.co.jp/icon.png'),
       ('3C4d5E6f7G8h9I0j1K2l3M4n5O', 'サービス株式会社', '高品質なサービスを展開', 'https://service.co.jp',
        'https://service.co.jp/icon.png'),
       ('4D5e6F7g8H9i0J1k2L3m4N5o6P', '株式会社デルタ', 'ITソリューションのプロバイダ', 'https://delta.co.jp',
        'https://delta.co.jp/icon.png'),
       ('5E6f7G8h9I0j1K2l3M4n5O6p7Q', 'エコー企業', '環境に優しい製品を展開', 'https://echo.co.jp',
        'https://echo.co.jp/icon.png'),
       ('6F7g8H9i0J1k2L3m4N5o6P7q8R', 'フォックス株式会社', 'サービスのイノベータ', 'https://fox.co.jp',
        'https://fox.co.jp/icon.png'),
       ('7G8h9I0j1K2l3M4n5O6p7Q8r9S', 'ゴルフ株式会社', 'スポーツ関連の商品製造', 'https://golf.co.jp',
        'https://golf.co.jp/icon.png'),
       ('8H9i0J1k2L3m4N5o6P7q8R9s0T', '株式会社ホテル', '高級ホテルの運営', 'https://hotel.co.jp',
        'https://hotel.co.jp/icon.png'),
       ('9I0j1K2l3M4n5O6p7Q8r9S0t1U', 'インディア企業', '国際的なビジネス展開', 'https://india.co.jp',
        'https://india.co.jp/icon.png'),
       ('0J1k2L3m4N5o6P7q8R9s0T1u2V', '株式会社ジャズ', '音楽関連の事業', 'https://jazz.co.jp',
        'https://jazz.co.jp/icon.png'),
       ('1K2l3M4n5O6p7Q8r9S0t1U2v3W', 'キロ株式会社', '物流・輸送業', 'https://kilo.co.jp',
        'https://kilo.co.jp/icon.png'),
       ('2L3m4N5o6P7q8R9s0T1u2V3w4X', '株式会社リマ', '広告業界のトップカンパニー', 'https://lima.co.jp',
        'https://lima.co.jp/icon.png'),
       ('3M4n5O6p7Q8r9S0t1U2v3W4x5Y', 'マイク企業', '電子機器の製造・販売', 'https://mike.co.jp',
        'https://mike.co.jp/icon.png'),
       ('4N5o6P7q8R9s0T1u2V3w4X5y6Z', '株式会社ノヴァ', '新技術の研究・開発', 'https://nova.co.jp',
        'https://nova.co.jp/icon.png'),
       ('5O6p7Q8r9S0t1U2v3W4x5Y6z7A', 'オスカー株式会社', '映画製作・配信', 'https://oscar.co.jp',
        'https://oscar.co.jp/icon.png'),
       ('6P7q8R9s0T1u2V3w4X5y6Z7a8B', '株式会社ペパー', '食品加工業', 'https://pepper.co.jp',
        'https://pepper.co.jp/icon.png'),
       ('7Q8r9S0t1U2v3W4x5Y6z7A8b9C', 'クイーン企業', '女性向け商品の製造・販売', 'https://queen.co.jp',
        'https://queen.co.jp/icon.png'),
       ('8R9s0T1u2V3w4X5y6Z7a8B9c0D', 'ロメオ株式会社', 'ファッション関連事業', 'https://romeo.co.jp',
        'https://romeo.co.jp/icon.png'),
       ('9S0t1U2v3W4x5Y6z7A8b9C0d1E', '株式会社シエラ', '旅行・観光業', 'https://sierra.co.jp',
        'https://sierra.co.jp/icon.png'),
       ('0T1u2V3w4X5y6Z7a8B9c0D1e2F', 'タンゴ企業', 'ダンススクール・関連商品の販売', 'https://tango.co.jp',
        'https://tango.co.jp/icon.png');
